from cards.cards import *
from game_state import GameState

taiga = Taiga()
elvish_spirit_guide = ElvishSpiritGuide()
simian_spirit_guide = SimianSpiritGuide()
tinder_wall = TinderWall()
desperate_ritual = DesperateRitual()
pyretic_ritual = PyreticRitual()
rite_of_flame = RiteOfFlame()
seething_song = SeethingSong()
empty_the_warrens = EmptyTheWarrens()
gitaxian_probe = GitaxianProbe()
land_grant = LandGrant()
lions_eye_diamond = LionsEyeDiamond()
lotus_petal = LotusPetal()
manamorphose = Manamorphose()
goblin_charbelcher = GoblinCharbelcher()
chrome_mox = ChromeMox()
burning_wish = BurningWish()
reforge_the_soul = ReforgeTheSoul()

game_state = GameState()
game_state.add_card(taiga, 1, 0)
game_state.add_card(elvish_spirit_guide, 4, 0)
game_state.add_card(simian_spirit_guide, 4, 0)
game_state.add_card(tinder_wall, 4, 0)
game_state.add_card(desperate_ritual, 4, 0)
game_state.add_card(pyretic_ritual, 3, 0)
game_state.add_card(rite_of_flame, 4, 0)
game_state.add_card(seething_song, 4, 0)
game_state.add_card(empty_the_warrens, 3, 1)
game_state.add_card(gitaxian_probe, 4, 0)
game_state.add_card(land_grant, 4, 0)
game_state.add_card(lions_eye_diamond, 4, 0)
game_state.add_card(lotus_petal, 4, 0)
game_state.add_card(manamorphose, 2, 0)
game_state.add_card(goblin_charbelcher, 4, 0)
game_state.add_card(chrome_mox, 3, 0)
game_state.add_card(burning_wish, 4, 0)
game_state.add_card(reforge_the_soul, 0, 1)

print(sum([game_state.deck[k] for k in game_state.deck]))